---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://{{ hostname }}/api/websites/{{ website_id }}/pageviews?startAt={{ ''now'' | date: ''%s'' | minus: lookback_period | times: 1000 }}&endAt={{ ''now'' | date: ''%s'' | times: 1000}}&unit=day&timezone={{ time_zone | url_encode}}'
polling_headers: Authorization=Bearer {{ api_key }}
id: 25370
custom_fields:
- keyname: doesnt_matter
  name: Umami Analytics
  field_type: author_bio
  description: Web analytics plugin for Umami
  github_url: https://github.com/nicell/trmnl-umami
  learn_more_url: https://umami.is/
  email_address: nick@winans.io
- keyname: lookback_period
  field_type: select
  options:
  - 7: 604800
  - 14: 1209600
  - 30: 2592000
  name: Lookback Period
  description: Time span of displayed data
  help_text: In days
- keyname: api_key
  field_type: password
  name: API Key
  description: Your Umami API key
- keyname: hostname
  field_type: string
  name: Hostname
  placeholder: umami.mydomain.com
  description: Host where Umami is hosted
- keyname: website_id
  field_type: string
  name: Website ID
  description: UUID of your website on Umami
- keyname: time_zone
  field_type: time_zone
  name: Time Zone
  description: Where are you located?
name: Umami Analytics
refresh_interval: 360
